<!-- <script src="/js/jquery-ui-1.10.3.custom.min.js"></script> -->
<!-- <script src="/js/jquery.ui.touch-punch.min.js"></script> -->
<!-- <script src="/js/bootstrap-select.js"></script> -->
<!-- <script src="/js/bootstrap-switch.js"></script> -->
<!-- <script src="/js/flatui-checkbox.js"></script> -->
<!-- <script src="/js/flatui-radio.js"></script> -->
<!-- <script src="/js/jquery.tagsinput.js"></script> -->
<!-- <script src="/js/jquery.placeholder.js"></script> -->
<!-- <script src="/js/jquery.stacktable.js"></script> -->
<!-- <script src="http://vjs.zencdn.net/4.3/video.js"></script> -->
<!-- <script src="/js/application.js"></script> -->

<script src="/bearded-beta/js/jquery-1.11.1.min.js"></script>
<script src="/bearded-beta/js/bootstrap.min.js"></script>
<script src="/bearded-beta/js/custom.js"></script>
<script src="/bearded-beta/js/jquery.fittext.js"></script>
<script src="/bearded-beta/js/custom.fittext.js"></script>
<script src="/bearded-beta/js/custom.navheight.js"></script>
<script src="/bearded-beta/js/custom.scrollto.js"></script>
<script src="/bearded-beta/js/custom.sharrre.js"></script>